spring.application.name=FixCity
spring.config.import=optional:file:.env[.properties]

spring.datasource.url=${POSTGRE_HOST}
spring.datasource.username=${POSTGRE_USERNAME}
spring.datasource.password=${POSTGRE_PASSWORD}

#JPA prop
#In PROD prima linie o sterg sau pun false, ddl-auto schimb la update
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

csc.base-url=${CSC_API_BASE_URL:https://api.countrystatecity.in/v1}
csc.api-key=${CSC_API_KEY:}

security.jwt.secret=${JWT_SECRET}
security.jwt.exp-minutes=${JWT_EXP_MINUTES}

cloudinary.url=${CLOUDINARY_URL}

stripe.secret-key=${STRIPE_SECRET_KEY}
stripe.price.urban=${STRIPE_PRICE_URBAN}
stripe.price.city-pro=${STRIPE_PRICE_CITY_PRO}
stripe.webhook.secret=${STRIPE_WEBHOOK_SECRET}

nominatim.base-url=${NOMINATIM_BASE_URL}
nominatim.user-agent=${NOMINATIM_USER_AGENT}

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
