spring.application.name=FixCity

spring.datasource.url=jdbc:postgresql://localhost:5432/fixcity
spring.datasource.username=postgres
spring.datasource.password=postgres

#JPA prop
#In PROD prima linie o sterg sau pun false, ddl-auto schimb la update
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

security.jwt.secret=jR5wFrFo9NRMMCWRIqz0WDcQiaTwCj1KBjQl1BL69ZQ/Rf07BpRZhdSt8HDM9vnV
security.jwt.exp-minutes=60

cloudinary.url=cloudinary://529433714264686:Frg7e6-h5XeaIQOSGO2mubzW0Pw@dpibfnkxb