package com.fixcity.fixcity.subscrption.enumeration;

public enum FeatureType {
    //URBAN
    PERIOD_FILTER,
    STATUS_HISTORY,
    BEFORE_AFTER_RESOLUTION,
    PERIOD_STATISTICS,
    TOP_PROBLEM_CATEGORIES,
    TOP_CRITICAL_ZONES,
    CSV_EXPORT,
    EXTENDED_ADMIN_ACCOUNTS,

    //CITY_PRO
    CITIZEN_CONFIRMATION_STATISTICS,
    AUTOMATIC_PRIORITY,
    PRIORITY_SCORE,
    AVERAGE_RESOLUTION_TIME,
    ADVANCED_STATISTICS,
}
