--
-- PostgreSQL database dump
--


-- Dumped from database version 17.0
-- Dumped by pg_dump version 18.1 (Homebrew)




--
-- Name: comments; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.comments (
    created_at timestamp(6) without time zone,
    id bigint NOT NULL,
    parent_comment_id bigint,
    report_id bigint,
    updated_at timestamp(6) without time zone,
    user_id bigint,
    text character varying(255)
);


--
-- Name: comments_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.comments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.comments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: confirmations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.confirmations (
    confirmed_at timestamp(6) without time zone,
    id bigint NOT NULL,
    report_id bigint NOT NULL,
    user_id bigint NOT NULL
);


--
-- Name: confirmations_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.confirmations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.confirmations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: municipalities; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.municipalities (
    id bigint NOT NULL,
    country character varying(255),
    country_iso2 character varying(255),
    name character varying(255),
    name_key character varying(255),
    state character varying(255),
    state_iso2 character varying(255),
    stripe_customer_id character varying(255)
);


--
-- Name: municipalities_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.municipalities ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.municipalities_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: municipality_requests; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.municipality_requests (
    created_at timestamp(6) without time zone,
    id bigint NOT NULL,
    reviewed_at timestamp(6) without time zone,
    user_id bigint,
    employee_position character varying(255),
    institution_name character varying(255),
    justification character varying(255),
    status character varying(255) NOT NULL,
    CONSTRAINT municipality_requests_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'APPROVED'::character varying, 'REJECTED'::character varying])::text[])))
);


--
-- Name: municipality_requests_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.municipality_requests ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.municipality_requests_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: reports; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.reports (
    latitude double precision NOT NULL,
    longitude double precision NOT NULL,
    created_at timestamp(6) without time zone,
    id bigint NOT NULL,
    municipality_id bigint,
    resolved_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    user_id bigint,
    address character varying(255),
    after_image_url character varying(255),
    category character varying(255),
    description character varying(255),
    image_url character varying(255),
    status character varying(255),
    title character varying(255),
    CONSTRAINT reports_category_check CHECK (((category)::text = ANY ((ARRAY['ROAD'::character varying, 'LIGHTING'::character varying, 'WASTE'::character varying, 'VANDALISM'::character varying, 'OTHER'::character varying])::text[]))),
    CONSTRAINT reports_status_check CHECK (((status)::text = ANY ((ARRAY['NEW'::character varying, 'IN_PROGRESS'::character varying, 'RESOLVED'::character varying])::text[])))
);


--
-- Name: reports_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.reports ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.reports_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: subscriptions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.subscriptions (
    cancel_at_period_end boolean NOT NULL,
    canceled_at timestamp(6) without time zone,
    created_at timestamp(6) without time zone,
    current_period_end timestamp(6) without time zone,
    current_period_start timestamp(6) without time zone,
    id bigint NOT NULL,
    municipality_id bigint,
    updated_at timestamp(6) without time zone,
    plan character varying(255) NOT NULL,
    status character varying(255) NOT NULL,
    stripe_subscription_id character varying(255) NOT NULL,
    CONSTRAINT subscriptions_plan_check CHECK (((plan)::text = ANY ((ARRAY['URBAN'::character varying, 'CITY_PRO'::character varying])::text[]))),
    CONSTRAINT subscriptions_status_check CHECK (((status)::text = ANY ((ARRAY['INCOMPLETE'::character varying, 'INCOMPLETE_EXPIRED'::character varying, 'TRIALING'::character varying, 'ACTIVE'::character varying, 'PAST_DUE'::character varying, 'CANCELED'::character varying, 'UNPAID'::character varying, 'PAUSED'::character varying])::text[])))
);


--
-- Name: subscriptions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.subscriptions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.subscriptions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    municipality_id bigint,
    email character varying(255),
    password character varying(255),
    role character varying(255),
    status character varying(255),
    username character varying(255),
    CONSTRAINT users_role_check CHECK (((role)::text = ANY ((ARRAY['ROLE_USER'::character varying, 'ROLE_MUNICIPAL_ADMIN'::character varying, 'ROLE_ADMIN'::character varying])::text[]))),
    CONSTRAINT users_status_check CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'LOCKED'::character varying])::text[])))
);


--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: comments comments_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.comments
    ADD CONSTRAINT comments_pkey PRIMARY KEY (id);


--
-- Name: confirmations confirmations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.confirmations
    ADD CONSTRAINT confirmations_pkey PRIMARY KEY (id);


--
-- Name: municipalities municipalities_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.municipalities
    ADD CONSTRAINT municipalities_pkey PRIMARY KEY (id);


--
-- Name: municipality_requests municipality_requests_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.municipality_requests
    ADD CONSTRAINT municipality_requests_pkey PRIMARY KEY (id);


--
-- Name: reports reports_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reports
    ADD CONSTRAINT reports_pkey PRIMARY KEY (id);


--
-- Name: subscriptions subscriptions_municipality_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.subscriptions
    ADD CONSTRAINT subscriptions_municipality_id_key UNIQUE (municipality_id);


--
-- Name: subscriptions subscriptions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.subscriptions
    ADD CONSTRAINT subscriptions_pkey PRIMARY KEY (id);


--
-- Name: confirmations uq_confirmation_user_report; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.confirmations
    ADD CONSTRAINT uq_confirmation_user_report UNIQUE (user_id, report_id);


--
-- Name: municipalities uq_municipal_canonical; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.municipalities
    ADD CONSTRAINT uq_municipal_canonical UNIQUE (country_iso2, state_iso2, name_key);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: confirmations fk2713gdbb1t0sl92kk97j5p0wt; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.confirmations
    ADD CONSTRAINT fk2713gdbb1t0sl92kk97j5p0wt FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: confirmations fk2no5e7kiaxhasbxdrmfnq3xgd; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.confirmations
    ADD CONSTRAINT fk2no5e7kiaxhasbxdrmfnq3xgd FOREIGN KEY (report_id) REFERENCES public.reports(id);


--
-- Name: reports fk2o32rer9hfweeylg7x8ut8rj2; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reports
    ADD CONSTRAINT fk2o32rer9hfweeylg7x8ut8rj2 FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: comments fk7h839m3lkvhbyv3bcdv7sm4fj; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.comments
    ADD CONSTRAINT fk7h839m3lkvhbyv3bcdv7sm4fj FOREIGN KEY (parent_comment_id) REFERENCES public.comments(id);


--
-- Name: comments fk8omq0tc18jd43bu5tjh6jvraq; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.comments
    ADD CONSTRAINT fk8omq0tc18jd43bu5tjh6jvraq FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: comments fkcq6hwtukw527pld91vsq40l0; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.comments
    ADD CONSTRAINT fkcq6hwtukw527pld91vsq40l0 FOREIGN KEY (report_id) REFERENCES public.reports(id);


--
-- Name: subscriptions fkdts259yxgd0kxix9ry22wnclj; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.subscriptions
    ADD CONSTRAINT fkdts259yxgd0kxix9ry22wnclj FOREIGN KEY (municipality_id) REFERENCES public.municipalities(id);


--
-- Name: reports fkg70grpfoh4ualv4x1jw9lmsiy; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.reports
    ADD CONSTRAINT fkg70grpfoh4ualv4x1jw9lmsiy FOREIGN KEY (municipality_id) REFERENCES public.municipalities(id);


--
-- Name: municipality_requests fkospje945bfn1inf73x25pw66u; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.municipality_requests
    ADD CONSTRAINT fkospje945bfn1inf73x25pw66u FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: users fkrnctccepsvko7k3odxg26cnp6; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT fkrnctccepsvko7k3odxg26cnp6 FOREIGN KEY (municipality_id) REFERENCES public.municipalities(id);


--
-- PostgreSQL database dump complete
--


